/** Generated by YAKINDU Statechart Tools code generator. */

#include "Statechart.h"

/*! \file
Implementation of the state machine 'Statechart'
*/




Statechart::Statechart() :
	viMyCounter(0),
	timerService(sc_null),
	isExecuting(false)
{
	for (sc_ushort state_vec_pos = 0; state_vec_pos < maxOrthogonalStates; ++state_vec_pos)
		stateConfVector[state_vec_pos] = Statechart_last_state;
	
	clearInEvents();
}

Statechart::~Statechart()
{
}


using namespace statechart_events;

SctEvent* Statechart::getNextEvent()
{
	SctEvent* nextEvent = 0;
	
	if(!inEventQueue.empty()) {
		nextEvent = inEventQueue.front();
		inEventQueue.pop_front();
	}
	
	return nextEvent;
}

void Statechart::dispatch_event(SctEvent * event)
{
	if(event == 0) {
		return;
	}
	switch(event->name)
	{
		case Statechart_IdleBlink_BLINK_time_event_0:
		{
			timeEvents[0] = true;
			break;
		}
		case Statechart_IdleBlink_BLINK_Blink_Turn_OFF_time_event_0:
		{
			timeEvents[1] = true;
			break;
		}
		case Statechart_IdleBlink_BLINK_Blink_Turn_ON_time_event_0:
		{
			timeEvents[2] = true;
			break;
		}
		case Statechart_IdleBlink_IDLE_time_event_0:
		{
			timeEvents[3] = true;
			break;
		}
		default:
			/* do nothing */
			break;
	}
	delete event;
}

void Statechart::iface_dispatch_event(SctEvent * event)
{
	switch(event->name)
	{
		default:
			/* do nothing */
			break;
	}
}
void Statechart::internal_dispatch_event(SctEvent * event)
{
	switch(event->name)
	{
		default:
			/* do nothing */
			break;
	}
}

StatechartEventName Statechart::getTimedEventName(sc_eventid evid)
{
	if (evid == (sc_eventid)(&timeEvents[0])) {
		return Statechart_IdleBlink_BLINK_time_event_0;
	}
	if (evid == (sc_eventid)(&timeEvents[1])) {
		return Statechart_IdleBlink_BLINK_Blink_Turn_OFF_time_event_0;
	}
	if (evid == (sc_eventid)(&timeEvents[2])) {
		return Statechart_IdleBlink_BLINK_Blink_Turn_ON_time_event_0;
	}
	if (evid == (sc_eventid)(&timeEvents[3])) {
		return Statechart_IdleBlink_IDLE_time_event_0;
	}
	return invalid_event;
}



sc_boolean Statechart::isActive() const
{
	return stateConfVector[0] != Statechart_last_state;
}

/* 
 * Always returns 'false' since this state machine can never become final.
 */
sc_boolean Statechart::isFinal() const
{
   return false;}

sc_boolean Statechart::check() {
	if(timerService == sc_null) {
		return false;
	}
	return true;
}


void Statechart::setTimerService(sc::timer::TimerServiceInterface* timerService_)
{
	this->timerService = timerService_;
}

sc::timer::TimerServiceInterface* Statechart::getTimerService()
{
	return timerService;
}

sc_integer Statechart::getNumberOfParallelTimeEvents() {
	return parallelTimeEventsCount;
}

void Statechart::raiseTimeEvent(sc_eventid evid)
{
	if ((evid >= (sc_eventid)timeEvents) && (evid < (sc_eventid)(&timeEvents[timeEventsCount])))
	{
		inEventQueue.push_back(new TimedSctEvent(getTimedEventName(evid)));
		runCycle();
	}
}


sc_boolean Statechart::isStateActive(StatechartStates state) const
{
	switch (state)
	{
		case IdleBlink_BLINK :
		{
			return (sc_boolean) (stateConfVector[SCVI_IDLEBLINK_BLINK] >= IdleBlink_BLINK && stateConfVector[SCVI_IDLEBLINK_BLINK] <= IdleBlink_BLINK_Blink_Turn_ON);
			break;
		}
		case IdleBlink_BLINK_Blink_Turn_OFF :
		{
			return (sc_boolean) (stateConfVector[SCVI_IDLEBLINK_BLINK_BLINK_TURN_OFF] == IdleBlink_BLINK_Blink_Turn_OFF);
			break;
		}
		case IdleBlink_BLINK_Blink_Turn_ON :
		{
			return (sc_boolean) (stateConfVector[SCVI_IDLEBLINK_BLINK_BLINK_TURN_ON] == IdleBlink_BLINK_Blink_Turn_ON);
			break;
		}
		case IdleBlink_IDLE :
		{
			return (sc_boolean) (stateConfVector[SCVI_IDLEBLINK_IDLE] == IdleBlink_IDLE);
			break;
		}
		default:
		{
			/* State is not active*/
			return false;
			break;
		}
	}
}


// implementations of all internal functions
/* Entry action for state 'BLINK'. */
void Statechart::enact_IdleBlink_BLINK()
{
	/* Entry action for state 'BLINK'. */
	timerService->setTimer(this, (sc_eventid)(&timeEvents[0]), (10 * 1000), false);
}

/* Entry action for state 'Turn_OFF'. */
void Statechart::enact_IdleBlink_BLINK_Blink_Turn_OFF()
{
	/* Entry action for state 'Turn_OFF'. */
	timerService->setTimer(this, (sc_eventid)(&timeEvents[1]), 750, false);
	opLedWrite(OFF);
	viMyCounter++;
}

/* Entry action for state 'Turn_ON'. */
void Statechart::enact_IdleBlink_BLINK_Blink_Turn_ON()
{
	/* Entry action for state 'Turn_ON'. */
	timerService->setTimer(this, (sc_eventid)(&timeEvents[2]), 250, false);
	opLedWrite(ON);
	viMyCounter++;
}

/* Entry action for state 'IDLE'. */
void Statechart::enact_IdleBlink_IDLE()
{
	/* Entry action for state 'IDLE'. */
	timerService->setTimer(this, (sc_eventid)(&timeEvents[3]), (5 * 1000), false);
}

/* Exit action for state 'BLINK'. */
void Statechart::exact_IdleBlink_BLINK()
{
	/* Exit action for state 'BLINK'. */
	timerService->unsetTimer(this, (sc_eventid)(&timeEvents[0]));
}

/* Exit action for state 'Turn_OFF'. */
void Statechart::exact_IdleBlink_BLINK_Blink_Turn_OFF()
{
	/* Exit action for state 'Turn_OFF'. */
	timerService->unsetTimer(this, (sc_eventid)(&timeEvents[1]));
}

/* Exit action for state 'Turn_ON'. */
void Statechart::exact_IdleBlink_BLINK_Blink_Turn_ON()
{
	/* Exit action for state 'Turn_ON'. */
	timerService->unsetTimer(this, (sc_eventid)(&timeEvents[2]));
}

/* Exit action for state 'IDLE'. */
void Statechart::exact_IdleBlink_IDLE()
{
	/* Exit action for state 'IDLE'. */
	timerService->unsetTimer(this, (sc_eventid)(&timeEvents[3]));
}

/* 'default' enter sequence for state BLINK */
void Statechart::enseq_IdleBlink_BLINK_default()
{
	/* 'default' enter sequence for state BLINK */
	enact_IdleBlink_BLINK();
	enseq_IdleBlink_BLINK_Blink_default();
}

/* 'default' enter sequence for state Turn_OFF */
void Statechart::enseq_IdleBlink_BLINK_Blink_Turn_OFF_default()
{
	/* 'default' enter sequence for state Turn_OFF */
	enact_IdleBlink_BLINK_Blink_Turn_OFF();
	stateConfVector[0] = IdleBlink_BLINK_Blink_Turn_OFF;
}

/* 'default' enter sequence for state Turn_ON */
void Statechart::enseq_IdleBlink_BLINK_Blink_Turn_ON_default()
{
	/* 'default' enter sequence for state Turn_ON */
	enact_IdleBlink_BLINK_Blink_Turn_ON();
	stateConfVector[0] = IdleBlink_BLINK_Blink_Turn_ON;
}

/* 'default' enter sequence for state IDLE */
void Statechart::enseq_IdleBlink_IDLE_default()
{
	/* 'default' enter sequence for state IDLE */
	enact_IdleBlink_IDLE();
	stateConfVector[0] = IdleBlink_IDLE;
}

/* 'default' enter sequence for region IdleBlink */
void Statechart::enseq_IdleBlink_default()
{
	/* 'default' enter sequence for region IdleBlink */
	react_IdleBlink__entry_Default();
}

/* 'default' enter sequence for region Blink */
void Statechart::enseq_IdleBlink_BLINK_Blink_default()
{
	/* 'default' enter sequence for region Blink */
	react_IdleBlink_BLINK_Blink__entry_Default();
}

/* Default exit sequence for state BLINK */
void Statechart::exseq_IdleBlink_BLINK()
{
	/* Default exit sequence for state BLINK */
	exseq_IdleBlink_BLINK_Blink();
	exact_IdleBlink_BLINK();
}

/* Default exit sequence for state Turn_OFF */
void Statechart::exseq_IdleBlink_BLINK_Blink_Turn_OFF()
{
	/* Default exit sequence for state Turn_OFF */
	stateConfVector[0] = Statechart_last_state;
	exact_IdleBlink_BLINK_Blink_Turn_OFF();
}

/* Default exit sequence for state Turn_ON */
void Statechart::exseq_IdleBlink_BLINK_Blink_Turn_ON()
{
	/* Default exit sequence for state Turn_ON */
	stateConfVector[0] = Statechart_last_state;
	exact_IdleBlink_BLINK_Blink_Turn_ON();
}

/* Default exit sequence for state IDLE */
void Statechart::exseq_IdleBlink_IDLE()
{
	/* Default exit sequence for state IDLE */
	stateConfVector[0] = Statechart_last_state;
	exact_IdleBlink_IDLE();
}

/* Default exit sequence for region IdleBlink */
void Statechart::exseq_IdleBlink()
{
	/* Default exit sequence for region IdleBlink */
	/* Handle exit of all possible states (of Statechart.IdleBlink) at position 0... */
	switch(stateConfVector[ 0 ])
	{
		case IdleBlink_BLINK_Blink_Turn_OFF :
		{
			exseq_IdleBlink_BLINK_Blink_Turn_OFF();
			exact_IdleBlink_BLINK();
			break;
		}
		case IdleBlink_BLINK_Blink_Turn_ON :
		{
			exseq_IdleBlink_BLINK_Blink_Turn_ON();
			exact_IdleBlink_BLINK();
			break;
		}
		case IdleBlink_IDLE :
		{
			exseq_IdleBlink_IDLE();
			break;
		}
		default:
			/* do nothing */
			break;
	}
}

/* Default exit sequence for region Blink */
void Statechart::exseq_IdleBlink_BLINK_Blink()
{
	/* Default exit sequence for region Blink */
	/* Handle exit of all possible states (of Statechart.IdleBlink.BLINK.Blink) at position 0... */
	switch(stateConfVector[ 0 ])
	{
		case IdleBlink_BLINK_Blink_Turn_OFF :
		{
			exseq_IdleBlink_BLINK_Blink_Turn_OFF();
			break;
		}
		case IdleBlink_BLINK_Blink_Turn_ON :
		{
			exseq_IdleBlink_BLINK_Blink_Turn_ON();
			break;
		}
		default:
			/* do nothing */
			break;
	}
}

/* Default react sequence for initial entry  */
void Statechart::react_IdleBlink_BLINK_Blink__entry_Default()
{
	/* Default react sequence for initial entry  */
	enseq_IdleBlink_BLINK_Blink_Turn_ON_default();
}

/* Default react sequence for initial entry  */
void Statechart::react_IdleBlink__entry_Default()
{
	/* Default react sequence for initial entry  */
	opLedInit();
	viMyCounter = 0;
	enseq_IdleBlink_IDLE_default();
}

sc_integer Statechart::react(const sc_integer transitioned_before) {
	/* State machine reactions. */
	return transitioned_before;
}

sc_integer Statechart::IdleBlink_BLINK_react(const sc_integer transitioned_before) {
	/* The reactions of state BLINK. */
	sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (timeEvents[0])
		{ 
			exseq_IdleBlink_BLINK();
			timeEvents[0] = false;
			enseq_IdleBlink_IDLE_default();
			react(0);
			transitioned_after = 0;
		} 
	} 
	/* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		transitioned_after = react(transitioned_before);
	} 
	return transitioned_after;
}

sc_integer Statechart::IdleBlink_BLINK_Blink_Turn_OFF_react(const sc_integer transitioned_before) {
	/* The reactions of state Turn_OFF. */
	sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (timeEvents[1])
		{ 
			exseq_IdleBlink_BLINK_Blink_Turn_OFF();
			timeEvents[1] = false;
			enseq_IdleBlink_BLINK_Blink_Turn_ON_default();
			IdleBlink_BLINK_react(0);
			transitioned_after = 0;
		} 
	} 
	/* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		transitioned_after = IdleBlink_BLINK_react(transitioned_before);
	} 
	return transitioned_after;
}

sc_integer Statechart::IdleBlink_BLINK_Blink_Turn_ON_react(const sc_integer transitioned_before) {
	/* The reactions of state Turn_ON. */
	sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (timeEvents[2])
		{ 
			exseq_IdleBlink_BLINK_Blink_Turn_ON();
			timeEvents[2] = false;
			enseq_IdleBlink_BLINK_Blink_Turn_OFF_default();
			IdleBlink_BLINK_react(0);
			transitioned_after = 0;
		} 
	} 
	/* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		transitioned_after = IdleBlink_BLINK_react(transitioned_before);
	} 
	return transitioned_after;
}

sc_integer Statechart::IdleBlink_IDLE_react(const sc_integer transitioned_before) {
	/* The reactions of state IDLE. */
	sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (timeEvents[3])
		{ 
			exseq_IdleBlink_IDLE();
			timeEvents[3] = false;
			enseq_IdleBlink_BLINK_default();
			react(0);
			transitioned_after = 0;
		} 
	} 
	/* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		transitioned_after = react(transitioned_before);
	} 
	return transitioned_after;
}

void Statechart::clearInEvents() {
	timeEvents[0] = false;
	timeEvents[1] = false;
	timeEvents[2] = false;
	timeEvents[3] = false;
}

void Statechart::microStep() {
	switch(stateConfVector[ 0 ])
	{
		case IdleBlink_BLINK_Blink_Turn_OFF :
		{
			IdleBlink_BLINK_Blink_Turn_OFF_react(-1);
			break;
		}
		case IdleBlink_BLINK_Blink_Turn_ON :
		{
			IdleBlink_BLINK_Blink_Turn_ON_react(-1);
			break;
		}
		case IdleBlink_IDLE :
		{
			IdleBlink_IDLE_react(-1);
			break;
		}
		default:
			/* do nothing */
			break;
	}
}

void Statechart::runCycle() {
	/* Performs a 'run to completion' step. */
	if (isExecuting)
	{ 
		return;
	} 
	isExecuting = true;
	dispatch_event(getNextEvent());
	do
	{ 
		microStep();
		clearInEvents();
		dispatch_event(getNextEvent());
	} while ((((timeEvents[0]) || (timeEvents[1])) || (timeEvents[2])) || (timeEvents[3]));
	isExecuting = false;
}

void Statechart::enter() {
	/* Activates the state machine. */
	if (isExecuting)
	{ 
		return;
	} 
	isExecuting = true;
	/* Default enter sequence for statechart Statechart */
	enseq_IdleBlink_default();
	isExecuting = false;
}

void Statechart::exit() {
	/* Deactivates the state machine. */
	if (isExecuting)
	{ 
		return;
	} 
	isExecuting = true;
	/* Default exit sequence for statechart Statechart */
	exseq_IdleBlink();
	isExecuting = false;
}

/* Can be used by the client code to trigger a run to completion step without raising an event. */
void Statechart::triggerWithoutEvent() {
	runCycle();
}

